USE [master]
GO
/****** Object:  Database [TempSooryenDemo]    Script Date: 4/8/2019 7:59:18 PM ******/
CREATE DATABASE [TempSooryenDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TempSooryenDemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\TempSooryenDemo.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TempSooryenDemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\TempSooryenDemo_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [TempSooryenDemo] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TempSooryenDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TempSooryenDemo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET ARITHABORT OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [TempSooryenDemo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TempSooryenDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TempSooryenDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TempSooryenDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TempSooryenDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TempSooryenDemo] SET  MULTI_USER 
GO
ALTER DATABASE [TempSooryenDemo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TempSooryenDemo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TempSooryenDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TempSooryenDemo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [TempSooryenDemo]
GO
/****** Object:  Table [dbo].[Notes]    Script Date: 4/8/2019 7:59:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Notes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](100) NULL,
	[Body] [nvarchar](max) NULL,
	[InsertDate] [datetime] NULL,
	[InsertUser] [int] NULL,
	[UpdateDate] [datetime] NULL,
	[UpdateUser] [int] NULL,
	[UserMaster] [nchar](10) NULL,
 CONSTRAINT [PK_Notes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[User]    Script Date: 4/8/2019 7:59:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [nvarchar](50) NOT NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](20) NOT NULL,
	[Email] [nvarchar](50) NULL,
	[Mobile] [nvarchar](10) NULL,
	[IsActive] [bit] NULL,
	[InsertDate] [datetime] NULL,
	[InsertUser] [int] NULL,
	[UpdateDate] [datetime] NULL,
	[UpdateUser] [int] NULL,
	[UserMaster] [nchar](10) NULL,
 CONSTRAINT [PK_UserMaster] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Notes]  WITH CHECK ADD  CONSTRAINT [FK_Notes_User] FOREIGN KEY([UpdateUser])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[Notes] CHECK CONSTRAINT [FK_Notes_User]
GO
ALTER TABLE [dbo].[Notes]  WITH CHECK ADD  CONSTRAINT [FK_Notes_User1] FOREIGN KEY([InsertUser])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[Notes] CHECK CONSTRAINT [FK_Notes_User1]
GO
USE [master]
GO
ALTER DATABASE [TempSooryenDemo] SET  READ_WRITE 
GO
